Traceback (most recent call last):
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#SHOW DIFFERENCES BY THE PRODUCT?

snow_depth_winter_means_N = compute_gridcell_winter_means(IS2SITMOGR4_v3.snow_depth, years=[2018,2019,2020])
snow_depth_winter_means_SM = compute_gridcell_winter_means(IS2SITMOGR4_v3.snow_depth_sm,  years=[2018,2019,2020])

staticArcticMaps(snow_depth_winter_means_N-snow_depth_winter_means_SM, dates=snow_depth_winter_means.time.values,set_cbarlabel = "NESOSIM - SnowModel (m)", cmap="RdBu", col_wrap=3, vmin=-0.2, vmax=0.2, out_str='snowdepth_winter_2018_2023_v2_v3')

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[11], line 6[0m
[1;32m      3[0m snow_depth_winter_means_N [38;5;241m=[39m compute_gridcell_winter_means(IS2SITMOGR4_v3[38;5;241m.[39msnow_depth, years[38;5;241m=[39m[[38;5;241m2018[39m,[38;5;241m2019[39m,[38;5;241m2020[39m])
[1;32m      4[0m snow_depth_winter_means_SM [38;5;241m=[39m compute_gridcell_winter_means(IS2SITMOGR4_v3[38;5;241m.[39msnow_depth_sm,  years[38;5;241m=[39m[[38;5;241m2018[39m,[38;5;241m2019[39m,[38;5;241m2020[39m])
[0;32m----> 6[0m staticArcticMaps(snow_depth_winter_means_N[38;5;241m-[39msnow_depth_winter_means_SM, dates[38;5;241m=[39m[43msnow_depth_winter_means[49m[38;5;241m.[39mtime[38;5;241m.[39mvalues,set_cbarlabel [38;5;241m=[39m [38;5;124m"[39m[38;5;124mNESOSIM - SnowModel (m)[39m[38;5;124m"[39m, cmap[38;5;241m=[39m[38;5;124m"[39m[38;5;124mRdBu[39m[38;5;124m"[39m, col_wrap[38;5;241m=[39m[38;5;241m3[39m, vmin[38;5;241m=[39m[38;5;241m-[39m[38;5;241m0.2[39m, vmax[38;5;241m=[39m[38;5;241m0.2[39m, out_str[38;5;241m=[39m[38;5;124m'[39m[38;5;124msnowdepth_winter_2018_2023_v2_v3[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'snow_depth_winter_means' is not defined

