Traceback (most recent call last):
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/akpetty/miniconda3/envs/is2book_p39_env/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import numpy as np
import xarray as xr
import pandas as pd
from datetime import date
import pyproj 
import scipy.interpolate 
from glob import glob
import matplotlib.pyplot as plt
from utils.read_data_utils import read_is2_data # This allows us to read the ICESAT2 data directly from the google storage bucket

# Ignore warnings in the notebook to improve display
import warnings
warnings.filterwarnings('ignore')

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 10[0m
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mglob[39;00m [38;5;28;01mimport[39;00m glob
[1;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m---> 10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mread_data_utils[39;00m [38;5;28;01mimport[39;00m read_is2_data [38;5;66;03m# This allows us to read the ICESAT2 data directly from the google storage bucket[39;00m
[1;32m     12[0m [38;5;66;03m# Ignore warnings in the notebook to improve display[39;00m
[1;32m     13[0m [38;5;28;01mimport[39;00m [38;5;21;01mwarnings[39;00m

[0;31mImportError[0m: cannot import name 'read_is2_data' from 'utils.read_data_utils' (/Users/akpetty/GitHub/icesat2-book/content/utils/read_data_utils.py)

